name: Build and Deploy Lesson

on:
  workflow_dispatch:  # Enables manual trigger from GitHub Actions UI

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv/
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.2"
          use-public-rspm: true

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install Dependencies
        run: |
          Rscript -e 'install.packages("sandpaper")'
          Rscript -e 'install.packages("renv")'
          Rscript -e 'renv::restore()'

      - name: Build Lesson
        run: |
          Rscript -e 'sandpaper::package_cache_trigger(TRUE)'
          Rscript -e 'sandpaper:::ci_deploy(md_branch = "md-outputs", site_branch = "gh-pages")'

  # The standard Carpentries workflows use the gh-pages branch directly
  # So we don't need the Actions deployment service
  # The deploy job has been removed
